{{- range .Values.nodes }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .branch }}-branch
type: Opaque
data:
  branch: "{{ .branch | b64enc }}"
  testnet: "{{ .testnet | quote | b64enc }}"
  name: "{{ .branch | b64enc }}"
  chainid: "{{ .chainid | quote | b64enc }}"  
{{- end }}
